
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.File;
import java.io.FileWriter;
import java.util.Objects;
import java.util.Scanner;

import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.TitledPane;

import javafx.scene.control.ListView;

import javafx.scene.control.TextArea;

import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

public class CookUI {
	@FXML
	private TitledPane readyPane;
	@FXML
	private Button cookButton;
	@FXML
	private ListView<String> readyList;
	@FXML
	private Button readyDetails;
	@FXML
	private TitledPane cookingPane;
	@FXML
	private Button finishButton;
	@FXML
	private ListView<String> cookingList;
	@FXML
	private Button cookingDetails;
	@FXML
	private TitledPane finishedPane;
	@FXML
	private Button finalizeButton;
	@FXML
	private ListView<String> finishedList;
	@FXML
	private Button finishedDetails;
	@FXML
	private AnchorPane detailsPane;
	@FXML
	private TextArea orderDetails;
	@FXML
	private Button okButton;

	// populate lists
	public void initialize() {
		try {
            //TODO
        	String orderNum = "";
            File orderFile = new File("Orders.txt");
            
            if (orderFile.isFile()) {
            	Scanner sc = new Scanner(orderFile);
            	while (sc.hasNextLine()) {
            		orderNum = sc.nextLine();
            		
            		File oFile = new File(orderNum + ".txt");
            		if (oFile.isFile()) {
                    	Scanner sc2 = new Scanner(oFile);
                    	String line = "";
                    	while (sc2.hasNextLine()) {
                    		line = sc2.nextLine();
                    	}
                    	line = line.substring(8);
                    	
                    	if (line.equals("Ready To Cook"))
                    		readyList.getItems().add(orderNum);
                    	else if (line.equals("Cooking"))
                    		cookingList.getItems().add(orderNum);
                    	else if (line.equals("READY"))
                    		finishedList.getItems().add(orderNum);
                    	sc2.close();
            		}
            	}
            sc.close();
            }
            else {
            	
            }
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
	}
	
	// Event Listener on Button[#cookButton].onAction
	@FXML
	public void orderCook(ActionEvent event) {
		try {
            changeStatus(readyList, "Status: Ready To Cook\n", "Status: Cooking");
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
	}
	
	// Event Listener on Button[#readyDetails].onAction
	@FXML
	public void getReadyDetails(ActionEvent event) {
		getDetails(readyList);
	}
	
	// Event Listener on Button[#finishButton].onAction
	@FXML
	public void orderReady(ActionEvent event) {
		// TODO Autogenerated
		try {
            //Email Simulation
            Stage emailUI = new Stage();
            Parent root = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("emailNotif.fxml")));
            emailUI.setTitle("Notification");
            emailUI.setScene(new Scene(root, 300, 150));
            emailUI.resizableProperty().setValue(Boolean.FALSE);
            emailUI.show();
            
            // move order to next table
            changeStatus(cookingList, "Status: Cooking\n", "Status: READY");
            
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
	}
	
	// Event Listener on Button[#cookingDetails].onAction
	@FXML
	public void getCookingDetails(ActionEvent event) {
		getDetails(cookingList);
	}
	
	// Event Listener on Button[#finalizeButton].onAction
	@FXML
	public void orderFinish(ActionEvent event) {
		try {
			
        } catch (Exception e) {
            // TODO: handle exception
            e.printStackTrace();
            System.err.println(e.getClass().getName() + ": " + e.getMessage());
        }
	}
	
	// Event Listener on Button[#finishedDetails].onAction
	@FXML
	public void getFinishedDetails(ActionEvent event) {
		getDetails(finishedList);
	}
	
	// Event Listener on Button[#okButton].onAction
	@FXML
	public void closeDetails(ActionEvent event) {
		detailsPane.setVisible(false);
	}
	
	private void getDetails(ListView<String> list) {
		ObservableList<String> selected = list.getSelectionModel().getSelectedItems();
		String order = selected.get(0);
		if (order != null)
		{
			try {
	            File oFile = new File(order + ".txt");
	            //placeholder credentials
	            if (oFile.isFile()) {
	            	Scanner sc = new Scanner(oFile);
	            	String line = "";
	            	while (sc.hasNextLine()) {
	            		line += (sc.nextLine() + "\n");
	            	}
	            sc.close();
	            orderDetails.setText(line);
	            detailsPane.setVisible(true);
	            }
	        } catch (Exception e) {
	            // TODO: handle exception
	            e.printStackTrace();
	            System.err.println(e.getClass().getName() + ": " + e.getMessage());
	        }
		}
	}
	
	private void changeStatus(ListView<String> list, String oldStatus, String newStatus) {
		ObservableList<String> selected = list.getSelectionModel().getSelectedItems();
		String order = selected.get(0);
		if (order != null)
		{
			try {
				File oFile = new File(order + ".txt");
				if (oFile.isFile()) {
					String oldContent = "";
	            	Scanner sc = new Scanner(oFile);
	            	while (sc.hasNextLine()) {
	            		oldContent += (sc.nextLine() + "\n");
	            	}
	            	sc.close();
	            	
	            	String newContent = oldContent.replaceAll(oldStatus, newStatus);
	            	
	            	FileWriter writer = new FileWriter(oFile);
	            	writer.write(newContent);
	            	writer.close();
	            	
	            	readyList.getItems().clear();
	            	cookingList.getItems().clear();
	            	finishedList.getItems().clear();
	            	initialize();
				}
				
			} catch (Exception e) {
	            // TODO: handle exception
	            e.printStackTrace();
	            System.err.println(e.getClass().getName() + ": " + e.getMessage());
	        }
		}
	}
}
